# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b_3S0HHjmkadahOBcYuaHrKvL17sxOgA
"""

import requests
import pandas as pd
from plyer import notification

def baixar_dados_bancos(url):
    resposta = requests.get(url)

    if resposta.ok:
        dados_bancos = resposta.json()
        return dados_bancos
    else:
        notification.notify(
            title='Erro de integração na API',
            message='Não foi possível baixar os dados',
            app_name='erro',
            timeout=10
        )
        return None

# URL da API dos bancos brasileiros
url_api_bancos = 'https://brasilapi.com.br/api/banks/v1'

dados_bancos = baixar_dados_bancos(url_api_bancos)

if dados_bancos:
    # Criando três DataFrames diferentes com as colunas selecionadas
    df_bancos1 = pd.DataFrame(dados_bancos)[['ispb','name', 'code', 'fullName']]
    df_bancos2 = pd.DataFrame(dados_bancos)[['name','fullName']]
    df_bancos3 = pd.DataFrame(dados_bancos)[['name', 'code']]

    # Exibindo as primeiras linhas de cada DataFrame
    print("DataFrame criado com sucesso:")
    display(df_bancos1.head(5))
    display(df_bancos2.head(5))
    display(df_bancos3.head(5))